<a href="https://colab.research.google.com/github/patryknextdoor/Data-Science-Bootcamp/blob/main/Data_Science_BootCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **STATISTICS  PROBABILITY AND LINEAR ALGEBRA**

# **Vectors - tablica liczb**

Wektor to tablica liczb, których
identyfikacja jest możliwa za pomocą
indeksu określającego położenie.
Wektory identyfikują punkty w
przestrzeni. Załóżmy, że mamy wektor
x. Pierwszym elementem tego wektora
jest x1, drugim x2, a ostatnim xn, co
przedstawiono na poniższym rysunku:

In [3]:
import numpy as np

In [4]:
A = np.array([3,6,8,1]) # wektor jako wiersz 7 row
A

array([3, 6, 8, 1])

In [8]:
A1 = np.array([[3],[6],[8],[1]]) # wektor jako kolumna / column
A1

array([[3],
       [6],
       [8],
       [1]])

# **Macierze - Matrix - dwuwymiarowa tablica liczb**


In [9]:
B = np.array([[3,7,4] , [9,3,5]])
B

array([[3, 7, 4],
       [9, 3, 5]])

In [13]:
C = np.arange(3,11)
C

array([ 3,  4,  5,  6,  7,  8,  9, 10])